name: GitHub Actions CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo '---Build started---'
          echo 'Building...' >> file.log
          echo '---Build complete---'

  test1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test1
        run: |
          echo '---Test1 started---'
          echo '1st Testing...' >> file.log
          echo '---Test1 complete---'

  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test2
        run: |
          echo '---Test2 started---'
          echo '2nd Testing...' >> file.log
          echo '---Test2 complete---'

  deploy:
    runs-on: ubuntu-latest
    needs: test2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Dev
        run: |
          echo '---DevDeploy started---'
          echo 'DevDeploy...' >> file.log
          echo '---DevDeploy complete---'
          cat file.log
          
  prod:
    runs-on: ubuntu-latest
    needs: test2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Prod
        run: |
          echo '---ProdDeploy started---'
          echo 'ProdDeploy...' >> file.log
          echo '---ProdDeploy complete---'
          cat file.log
