name: GitHub Actions CI/CD

env:
  LOG_FILE: file.log

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo '---Build started---'
          echo 'Building...' >> ${{ env.LOG_FILE }}
          echo '---Build complete---'

  test1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test1
        run: |
          echo '---Test1 started---'
          echo '1st Testing...' >> ${{ env.LOG_FILE }}
          echo '---Test1 complete---'

  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: Test2
        run: |
          echo '---Test2 started---'
          echo '2nd Testing...' >> ${{ env.LOG_FILE }}
          echo '---Test2 complete---'

  deploy:
    runs-on: ubuntu-latest
    needs: test2
    steps:
      - name: Deploy to Dev
        run: |
          echo '---DevDeploy started---'
          echo 'DevDeploy...' >> ${{ env.LOG_FILE }}
          echo '---DevDeploy complete---'
          cat ${{ env.LOG_FILE }}
          
  prod:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Deploy to Prod
        run: |
          echo '---ProdDeploy started---'
          echo 'ProdDeploy...' >> ${{ env.LOG_FILE }}
          echo '---ProdDeploy complete---'
          cat ${{ env.LOG_FILE }}
